public with sharing class Constants {
    // Result__c.Status__c
    public static final String RESULT_FAIL = 'Fail';
    public static final String RESULT_SUCCESS = 'Success';
    public static final String RESULT_UNSURE = 'Unsure';

    // Analysis__c.Status__c
    public static final String ANALYSIS_FAIL = 'Failed';
    public static final String ANALYSIS_SUCCESS = 'Successful';
    public static final String ANALYSIS_ERROR = 'Error';
}
